default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode

development:
  <<: *default
  database: test_guru_development
  username: aazdb  
  password: MyPassword
  host: localhost  
  port: 5432

test:
  <<: *default
  database: test_guru_test
  username: aazdb  
  password: MyPassword
  host: localhost  
  port: 5432

production:
  <<: *default
  database: test_guru_production
